server:
  port: 8001
  servlet:
    context-path: /member

#数据库连接
spring:
  datasource:
    url: jdbc:mysql://116.62.143.162:3306/train-member?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: mq6jQ6
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: member
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com.poss.mapper: trace