server:
  port: 8000

spring:
  cloud:
    gateway:
      # 网关全局跨域配置
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
        # 解决options请求被拦截的问题
        add-to-simple-url-handler-mapping: true
      
      routes:
        - id: member
          uri: http://127.0.0.1:8001
          predicates:
            - Path=/member/**
        - id: business
          uri: http://127.0.0.1:8002
          predicates:
            - Path=/business/**
        - id: batch
          uri: http://127.0.0.1:8003
          predicates:
            - Path=/batch/**